### ISSUE TITLE
IOS issue : invalid redeclaration of 'SwiftEntryPlugin'

### ISSUE THREAD

**Issue by AmineLAHRIM** [MickaelHrndz/entry#1]
#plugin version
entry: ^0.0.2+2

https://i.ibb.co/BjqpDGp/Screenshot-2021-05-05-at-3-16-33-am.png

#devices & IOS versions
real device iPhone 6  
ios 12.5.2

also in iPhone 12 pro simulator
ios 14.2

Xcode's output:
↳
    /Users/aminelahrim/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/entry-0.0.2+2/ios/Classes/SwiftAnimateInPlugin.swift:4:14: error: invalid redeclaration of 'SwiftEntryPlugin'
    public class SwiftEntryPlugin: NSObject, FlutterPlugin {
                 ^
    /Users/aminelahrim/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/entry-0.0.2+2/ios/Classes/SwiftEntryPlugin.swift:4:14: note: 'SwiftEntryPlugin' previously declared here
    public class SwiftEntryPlugin: NSObject, FlutterPlugin {
                 ^
    /Users/aminelahrim/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/entry-0.0.2+2/ios/Classes/SwiftEntryPlugin.swift:4:14: error: invalid redeclaration of 'SwiftEntryPlugin'
    public class SwiftEntryPlugin: NSObject, FlutterPlugin {
                 ^
    /Users/aminelahrim/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/entry-0.0.2+2/ios/Classes/SwiftAnimateInPlugin.swift:4:14: note: 'SwiftEntryPlugin' previously declared here
    public class SwiftEntryPlugin: NSObject, FlutterPlugin {

**Comment by AmineLAHRIM** [comment]
The solution that I found is 
1. download the package manually from pub.dev
2. copy entry.dart file into the project
3. add https://pub.dev/packages/simple_animations package into the project
4. Done

**Comment by MickaelHrndz** [comment]
Thank you for reporting the issue, I'll look into it asap

**Comment by MickaelHrndz** [comment]
It should be fixed with `^0.0.3`

**Comment by AmineLAHRIM** [comment]
@MickaelHrndz Thank you

**Comment by MickaelHrndz** [comment]
@AmineLAHRIM You're welcome :)
