### ISSUE TITLE
Flutter 3.13 Error

### ISSUE THREAD

**Issue by g1henx** [MickaelHrndz/entry#10]
i'm getting this error:
Error (Xcode):
../../../.pub-cache/hosted/pub.dev/simple_animations-5.0.0+3/lib/animation_mixin/animation_mixin.
dart:139:56: Error: A value of type 'ValueListenable<bool>' can't be assigned to a variable of
type 'ValueNotifier<bool>'.
I've been researching and it is fixed in simple_animations last version, so could you update the dependency?
Thanks in advance.

**Comment by MickaelHrndz** [comment]
Hello @g1henx,

Sorry for not seeing your issue sooner, and thank you for reporting this. I just released the 0.0.9 version which updates that simple_animations dependency to 5.0.2.
Please let me know if it fixes your issue, just to be sure.

**Comment by MickaelHrndz** [comment]
I'll close the issue now, but feel free to still let me know if it's good for you.
