### ISSUE TITLE
Delay rarely working correctly

### ISSUE THREAD

**Issue by reesz** [MickaelHrndz/entry#11]
Really love the simplicity of this package, thanks for publishing it!

When I try to stagger different `Entry` widgets with delays, it only rarely really takes that delay into account.

Here's an abstracted example of what I'm trying to do:
```dart
Column(
  children: [
    Entry(
      visible: playAnimation,
      duration: const Duration(milliseconds: 300),
      opacity: 0,
      yOffset: 20,
      child: Text("Headline 1"),
    ),
    Entry(
      visible: playAnimation,
      duration: const Duration(milliseconds: 300),
      delay: const Duration(seconds: 2),
      opacity: 0,
      yOffset: 20,
      child: Text("Headline 2"),
    ),
  ],
);
```

Even picking a definitely noticable delay like 2 seconds, both animations play at the same time.
Sometimes it seems to take the delay into account; i can't definitely say when that is. Possibly the very first animation after app start? But in 99% of times, it just ignores the delay, when playing the animation.

Let me know if I'm missing something or can provide anything else to help out. Flutter doctor output below.

---

<details>
  <summary>flutter doctor -v</summary>

```
❯ fvm flutter doctor -v
[!] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-arm64, locale de-DE)
    • Flutter version 3.13.4 on channel stable at /Users/reesz/fvm/versions/stable
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/reesz/fvm/versions/stable. Consider adding /Users/reesz/fvm/versions/stable/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (2 weeks ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Finch (mobile)  • 00008101-000A09113488001E • ios            • iOS 16.6 20G75
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.
```
</details>

**Comment by MickaelHrndz** [comment]
Thank you for using it, I'm glad you love it 😄 

You're right, the delay is only taken into account for **the first animation**. Toggling the `visible` parameter plays the animation back and forth, but without delay. 

I'm relying on the [simple_animations](https://pub.dev/packages/simple_animations)'s `CustomAnimationBuilder` widget for that. It allowed me to implement the `visible` parameter while keeping `Entry` a stateless widget. But that means I'm dependent on its behavior.

I just tried to find a way to delay the animation when toggling `visible`, but to no avail. Frankly, I'm not even fully convinced that it should be the behavior. My reasoning is that for the user, delaying `Entry` being inserted into the tree is not natural, but delaying the `visible` parameter being toggled, far more.

I'll close the issue for now, but you're welcome to argue more.

**Comment by harkairt** [comment]
It plays the animation without delay when the widget itself is being built more than once. 
For the first time the delay works well, but once it rebuilds it start the animation right away.

**Comment by MickaelHrndz** [comment]
@harkairt could you please provide a minimal reproducible example ? I tried with the repo's [example project](https://github.com/MickaelHrndz/entry/tree/master/example) and it seems to work fine.
