### ISSUE TITLE
Rebuild along with Entry.all

### ISSUE THREAD

**Issue by rirjkl19** [MickaelHrndz/entry#4]
I would like to ask if its possible to re-trigger the `Entry ` animation event on rebuild? I'm using flutter_bloc as a state management (but I'm using the cubits) . Here is a sample snippet.

``` dart
BlocBuilder<SomeCubit,SomeState>(
  bloc: someCubitInstance,
  builder: (context,state) {
    if (state is StateLoading) {
      return SomeLoadingWidget();
    } else if (state is StateSuccess) {
      return Entry.all(SomeDetailedWidget());  // Does trigger only once on stateless/stateful rebuild.
    
    ... some code..
    } else if (state is fail.....){
    ... more code here
    }
   ... and more irrelevant code..
  }
};
```
The Entry.all does not work. How do I make this work? I've posted this in StackOverFlow but haven't received any comments. 

Thanks in advance!

**Comment by MickaelHrndz** [comment]
Widgets will be recreated if you give them a different key. Set the key to `key: Key(random.nextDouble().toString())` to make it recreate every time it's rebuilt.

**Comment by rirjkl19** [comment]
Thanks you for the reply! I forgot about the flutter keys! I've been relying on the builder and treat all widgets like a common widget (containers). Anyway thank you for the help and for this awesome package you made it is now considered a must in all of my projects 😁

**Comment by MickaelHrndz** [comment]
You're welcome, and thank you for the kind words 😊
