### ISSUE TITLE
Update simple_animations Dependency

### ISSUE THREAD

**Issue by jtmuller5** [MickaelHrndz/entry#6]
Entry currently depends on simple_animations 3.0.1. It looks like the newest version of that package is 4.0.0.

**Comment by MickaelHrndz** [comment]
I'll make an update this week-end, thank you for letting me know !

**Comment by jtmuller5** [comment]
No problem! I also submitted a PR that has a new EntryExit widget which can animate a widget into and out of view. The constructor is basically the same but it has an additional "visible" property.

I've mainly found the reverse animation useful for showing popups/overlays. Would this be something you'd want to add to the entry package?

**Comment by MickaelHrndz** [comment]
I just published 0.0.6 with that dependency update. As for your PR (#7), I answered there.
