### ISSUE TITLE
and xOffset :)

### ISSUE THREAD

**Issue by aktxyz** [MickaelHrndz/entry#8]
https://github.com/MickaelHrndz/entry/blob/7505b0c93c53752f239851b6cd824002e6d0306b/lib/entry.dart#L48

**Comment by MickaelHrndz** [comment]
Nice catch, thanks :) Solved with the 0.0.7 release

https://github.com/MickaelHrndz/entry/blob/9ef5e9f2c1c896ca98772ab29af2d93d464723f0/lib/entry.dart#L52
